### ISSUE TITLE
Pane layout changes

### ISSUE THREAD

**Issue by jimmybgammyknee** [awaisc/motifOverlapR#5]
![img_2561](https://user-images.githubusercontent.com/1755973/34660419-24c1417c-f492-11e7-8f54-0f5378b2781e.JPG)

**Comment by awaisc** [comment]
![screen shot 2018-01-11 at 3 22 32 am](https://user-images.githubusercontent.com/25577229/34784875-75431abe-f67f-11e7-8007-6d934720e348.png)
![screen shot 2018-01-11 at 3 24 02 am](https://user-images.githubusercontent.com/25577229/34784885-79e74194-f67f-11e7-9c43-0d7adc6b3ee7.png)
![screen shot 2018-01-11 at 3 25 11 am](https://user-images.githubusercontent.com/25577229/34784936-9776b2bc-f67f-11e7-9329-5334b302f1cc.png)
![screen shot 2018-01-11 at 3 26 44 am](https://user-images.githubusercontent.com/25577229/34784944-9c41b9fe-f67f-11e7-8581-d1ddff5073f0.png)
![screen shot 2018-01-11 at 3 31 19 am](https://user-images.githubusercontent.com/25577229/34785072-002b29b4-f680-11e7-970b-fedb1d6f70f0.png)


Here how it currently looks on my mac, I made and optimised it for my ubunutu which has a different aspect ratio and number of pixels. 

Additionally, it appears that data tables do not render within the specified box requirements
