### ISSUE TITLE
Additional enhancer annotations

### ISSUE THREAD

**Issue by jimmybgammyknee** [awaisc/motifOverlapR#6]
Add additional enhancer information for overlapping rather than just ones that have a gene target (FANTOM5). Also add a heatmap next to the first tab to show which ChromHMM state overlaps each predicted site

**Comment by awaisc** [comment]
![screen shot 2018-01-11 at 3 24 02 am](https://user-images.githubusercontent.com/25577229/34785393-e99a84f0-f680-11e7-9d6e-26cb537333f5.png)


So this table has all the information you've requested - just not the heat map format you wanted for the epigenomic state the motif is located within

**Comment by jimmybgammyknee** [comment]
That looks really good. Might need to specific where the data is from too
